#  spring.application.name=web
#    spring.datasource.url=jdbc:postgresql://localhost:4444/it_p
#    spring.datasource.username=admin
#    #spring.datasource.password=${DB_PASSWORD}
#    spring.datasource.password=admin
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.show-sql=true
#    #spring.jpa.properties.hibernate.connection.autocommit=false
#
#    spring.datasource.hikari.auto-commit=false
#    spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true

#--module-path "D:\IntelliJ IDEA\JavaFX\openjfx-24.0.1_windows-x64_bin-sdk\javafx-sdk-24.0.1\lib" --add-modules javafx.controls,javafx.fxml



spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: Client